// generated by cdk8s
import { ApiObject, GroupVersionKind } from 'cdk8s';
import { Construct } from 'constructs';

/**
 * ConsoleQuickStart is an extension for guiding user through various workflows in the OpenShift web console.
 *
 * @schema ConsoleQuickStart
 */
export class ConsoleQuickStart extends ApiObject {
  /**
   * Returns the apiVersion and kind for "ConsoleQuickStart"
   */
  public static readonly GVK: GroupVersionKind = {
    apiVersion: 'console.openshift.io/v1',
    kind: 'ConsoleQuickStart',
  }

  /**
   * Renders a Kubernetes manifest for "ConsoleQuickStart".
   *
   * This can be used to inline resource manifests inside other objects (e.g. as templates).
   *
   * @param props initialization props
   */
  public static manifest(props: ConsoleQuickStartProps): any {
    return {
      ...ConsoleQuickStart.GVK,
      ...props,
    };
  }

  /**
   * Defines a "ConsoleQuickStart" API object
   * @param scope the scope in which to define this object
   * @param id a scope-local name for the object
   * @param props initialization props
   */
  public constructor(scope: Construct, id: string, props: ConsoleQuickStartProps) {
    super(scope, id, ConsoleQuickStart.manifest(props));
  }
}

/**
 * ConsoleQuickStart is an extension for guiding user through various workflows in the OpenShift web console.
 *
 * @schema ConsoleQuickStart
 */
export interface ConsoleQuickStartProps {
  /**
   * @schema ConsoleQuickStart#metadata
   */
  readonly metadata?: any;

  /**
   * ConsoleQuickStartSpec is the desired quick start configuration.
   *
   * @schema ConsoleQuickStart#spec
   */
  readonly spec: ConsoleQuickStartSpec;

}

/**
 * ConsoleQuickStartSpec is the desired quick start configuration.
 *
 * @schema ConsoleQuickStartSpec
 */
export interface ConsoleQuickStartSpec {
  /**
   * accessReviewResources contains a list of resources that the user's access will be reviewed against in order for the user to complete the Quick Start. The Quick Start will be hidden if any of the access reviews fail.
   *
   * @schema ConsoleQuickStartSpec#accessReviewResources
   */
  readonly accessReviewResources?: ConsoleQuickStartSpecAccessReviewResources[];

  /**
   * conclusion sums up the Quick Start and suggests the possible next steps. (includes markdown)
   *
   * @schema ConsoleQuickStartSpec#conclusion
   */
  readonly conclusion?: string;

  /**
   * description is the description of the Quick Start. (includes markdown)
   *
   * @schema ConsoleQuickStartSpec#description
   */
  readonly description: string;

  /**
   * displayName is the display name of the Quick Start.
   *
   * @schema ConsoleQuickStartSpec#displayName
   */
  readonly displayName: string;

  /**
   * durationMinutes describes approximately how many minutes it will take to complete the Quick Start.
   *
   * @schema ConsoleQuickStartSpec#durationMinutes
   */
  readonly durationMinutes: number;

  /**
   * icon is a base64 encoded image that will be displayed beside the Quick Start display name. The icon should be an vector image for easy scaling. The size of the icon should be 40x40.
   *
   * @schema ConsoleQuickStartSpec#icon
   */
  readonly icon?: string;

  /**
   * introduction describes the purpose of the Quick Start. (includes markdown)
   *
   * @schema ConsoleQuickStartSpec#introduction
   */
  readonly introduction: string;

  /**
   * nextQuickStart is a list of the following Quick Starts, suggested for the user to try.
   *
   * @schema ConsoleQuickStartSpec#nextQuickStart
   */
  readonly nextQuickStart?: string[];

  /**
   * prerequisites contains all prerequisites that need to be met before taking a Quick Start. (includes markdown)
   *
   * @schema ConsoleQuickStartSpec#prerequisites
   */
  readonly prerequisites?: string[];

  /**
   * tags is a list of strings that describe the Quick Start.
   *
   * @schema ConsoleQuickStartSpec#tags
   */
  readonly tags?: string[];

  /**
   * tasks is the list of steps the user has to perform to complete the Quick Start.
   *
   * @schema ConsoleQuickStartSpec#tasks
   */
  readonly tasks: ConsoleQuickStartSpecTasks[];

}

/**
 * ResourceAttributes includes the authorization attributes available for resource requests to the Authorizer interface
 *
 * @schema ConsoleQuickStartSpecAccessReviewResources
 */
export interface ConsoleQuickStartSpecAccessReviewResources {
  /**
   * Group is the API Group of the Resource.  "*" means all.
   *
   * @schema ConsoleQuickStartSpecAccessReviewResources#group
   */
  readonly group?: string;

  /**
   * Name is the name of the resource being requested for a "get" or deleted for a "delete". "" (empty) means all.
   *
   * @schema ConsoleQuickStartSpecAccessReviewResources#name
   */
  readonly name?: string;

  /**
   * Namespace is the namespace of the action being requested.  Currently, there is no distinction between no namespace and all namespaces "" (empty) is defaulted for LocalSubjectAccessReviews "" (empty) is empty for cluster-scoped resources "" (empty) means "all" for namespace scoped resources from a SubjectAccessReview or SelfSubjectAccessReview
   *
   * @schema ConsoleQuickStartSpecAccessReviewResources#namespace
   */
  readonly namespace?: string;

  /**
   * Resource is one of the existing resource types.  "*" means all.
   *
   * @schema ConsoleQuickStartSpecAccessReviewResources#resource
   */
  readonly resource?: string;

  /**
   * Subresource is one of the existing resource types.  "" means none.
   *
   * @schema ConsoleQuickStartSpecAccessReviewResources#subresource
   */
  readonly subresource?: string;

  /**
   * Verb is a kubernetes resource API verb, like: get, list, watch, create, update, delete, proxy.  "*" means all.
   *
   * @schema ConsoleQuickStartSpecAccessReviewResources#verb
   */
  readonly verb?: string;

  /**
   * Version is the API Version of the Resource.  "*" means all.
   *
   * @schema ConsoleQuickStartSpecAccessReviewResources#version
   */
  readonly version?: string;

}

/**
 * ConsoleQuickStartTask is a single step in a Quick Start.
 *
 * @schema ConsoleQuickStartSpecTasks
 */
export interface ConsoleQuickStartSpecTasks {
  /**
   * description describes the steps needed to complete the task. (includes markdown)
   *
   * @schema ConsoleQuickStartSpecTasks#description
   */
  readonly description: string;

  /**
   * review contains instructions to validate the task is complete. The user will select 'Yes' or 'No'. using a radio button, which indicates whether the step was completed successfully.
   *
   * @schema ConsoleQuickStartSpecTasks#review
   */
  readonly review?: ConsoleQuickStartSpecTasksReview;

  /**
   * summary contains information about the passed step.
   *
   * @schema ConsoleQuickStartSpecTasks#summary
   */
  readonly summary?: ConsoleQuickStartSpecTasksSummary;

  /**
   * title describes the task and is displayed as a step heading.
   *
   * @schema ConsoleQuickStartSpecTasks#title
   */
  readonly title: string;

}

/**
 * review contains instructions to validate the task is complete. The user will select 'Yes' or 'No'. using a radio button, which indicates whether the step was completed successfully.
 *
 * @schema ConsoleQuickStartSpecTasksReview
 */
export interface ConsoleQuickStartSpecTasksReview {
  /**
   * failedTaskHelp contains suggestions for a failed task review and is shown at the end of task. (includes markdown)
   *
   * @schema ConsoleQuickStartSpecTasksReview#failedTaskHelp
   */
  readonly failedTaskHelp: string;

  /**
   * instructions contains steps that user needs to take in order to validate his work after going through a task. (includes markdown)
   *
   * @schema ConsoleQuickStartSpecTasksReview#instructions
   */
  readonly instructions: string;

}

/**
 * summary contains information about the passed step.
 *
 * @schema ConsoleQuickStartSpecTasksSummary
 */
export interface ConsoleQuickStartSpecTasksSummary {
  /**
   * failed briefly describes the unsuccessfully passed task. (includes markdown)
   *
   * @schema ConsoleQuickStartSpecTasksSummary#failed
   */
  readonly failed: string;

  /**
   * success describes the succesfully passed task.
   *
   * @schema ConsoleQuickStartSpecTasksSummary#success
   */
  readonly success: string;

}

