// generated by cdk8s
import { ApiObject, GroupVersionKind } from 'cdk8s';
import { Construct } from 'constructs';

/**
 * ConsoleDocumentation is the Schema for the consoledocumentations API
 *
 * @schema ConsoleDocumentation
 */
export class ConsoleDocumentation extends ApiObject {
  /**
   * Returns the apiVersion and kind for "ConsoleDocumentation"
   */
  public static readonly GVK: GroupVersionKind = {
    apiVersion: 'documentation.console.openshift.io/v1alpha1',
    kind: 'ConsoleDocumentation',
  }

  /**
   * Renders a Kubernetes manifest for "ConsoleDocumentation".
   *
   * This can be used to inline resource manifests inside other objects (e.g. as templates).
   *
   * @param props initialization props
   */
  public static manifest(props: ConsoleDocumentationProps = {}): any {
    return {
      ...ConsoleDocumentation.GVK,
      ...props,
    };
  }

  /**
   * Defines a "ConsoleDocumentation" API object
   * @param scope the scope in which to define this object
   * @param id a scope-local name for the object
   * @param props initialization props
   */
  public constructor(scope: Construct, id: string, props: ConsoleDocumentationProps = {}) {
    super(scope, id, ConsoleDocumentation.manifest(props));
  }
}

/**
 * ConsoleDocumentation is the Schema for the consoledocumentations API
 *
 * @schema ConsoleDocumentation
 */
export interface ConsoleDocumentationProps {
  /**
   * @schema ConsoleDocumentation#metadata
   */
  readonly metadata?: any;

  /**
   * ConsoleDocumentationSpec defines the desired state of ConsoleDocumentation
   *
   * @schema ConsoleDocumentation#spec
   */
  readonly spec?: ConsoleDocumentationSpec;

}

/**
 * ConsoleDocumentationSpec defines the desired state of ConsoleDocumentation
 *
 * @schema ConsoleDocumentationSpec
 */
export interface ConsoleDocumentationSpec {
  /**
   * @schema ConsoleDocumentationSpec#appName
   */
  readonly appName?: string;

  /**
   * @schema ConsoleDocumentationSpec#description
   */
  readonly description?: string;

  /**
   * @schema ConsoleDocumentationSpec#displayName
   */
  readonly displayName?: string;

  /**
   * @schema ConsoleDocumentationSpec#durationMinutes
   */
  readonly durationMinutes: number;

  /**
   * @schema ConsoleDocumentationSpec#featureFlag
   */
  readonly featureFlag?: string;

  /**
   * @schema ConsoleDocumentationSpec#icon
   */
  readonly icon?: string;

  /**
   * @schema ConsoleDocumentationSpec#img
   */
  readonly img?: string;

  /**
   * @schema ConsoleDocumentationSpec#markDown
   */
  readonly markDown?: string;

  /**
   * @schema ConsoleDocumentationSpec#provider
   */
  readonly provider?: string;

  /**
   * @schema ConsoleDocumentationSpec#type
   */
  readonly type?: string;

  /**
   * @schema ConsoleDocumentationSpec#url
   */
  readonly url?: string;

}

