# permissions for end users to view consoleapplications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: consoleapplication-viewer-role
rules:
- apiGroups:
  - applications.console.openshift.io
  resources:
  - consoleapplications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - applications.console.openshift.io
  resources:
  - consoleapplications/status
  verbs:
  - get
