// +build !ignore_autogenerated

/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	authorizationv1 "k8s.io/api/authorization/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RhodsQuickStart) DeepCopyInto(out *RhodsQuickStart) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RhodsQuickStart.
func (in *RhodsQuickStart) DeepCopy() *RhodsQuickStart {
	if in == nil {
		return nil
	}
	out := new(RhodsQuickStart)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RhodsQuickStart) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RhodsQuickStartList) DeepCopyInto(out *RhodsQuickStartList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RhodsQuickStart, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RhodsQuickStartList.
func (in *RhodsQuickStartList) DeepCopy() *RhodsQuickStartList {
	if in == nil {
		return nil
	}
	out := new(RhodsQuickStartList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RhodsQuickStartList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RhodsQuickStartSpec) DeepCopyInto(out *RhodsQuickStartSpec) {
	*out = *in
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Prerequisites != nil {
		in, out := &in.Prerequisites, &out.Prerequisites
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Tasks != nil {
		in, out := &in.Tasks, &out.Tasks
		*out = make([]RhodsQuickStartTask, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NextQuickStart != nil {
		in, out := &in.NextQuickStart, &out.NextQuickStart
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AccessReviewResources != nil {
		in, out := &in.AccessReviewResources, &out.AccessReviewResources
		*out = make([]authorizationv1.ResourceAttributes, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RhodsQuickStartSpec.
func (in *RhodsQuickStartSpec) DeepCopy() *RhodsQuickStartSpec {
	if in == nil {
		return nil
	}
	out := new(RhodsQuickStartSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RhodsQuickStartStatus) DeepCopyInto(out *RhodsQuickStartStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RhodsQuickStartStatus.
func (in *RhodsQuickStartStatus) DeepCopy() *RhodsQuickStartStatus {
	if in == nil {
		return nil
	}
	out := new(RhodsQuickStartStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RhodsQuickStartTask) DeepCopyInto(out *RhodsQuickStartTask) {
	*out = *in
	if in.Review != nil {
		in, out := &in.Review, &out.Review
		*out = new(RhodsQuickStartTaskReview)
		**out = **in
	}
	if in.Summary != nil {
		in, out := &in.Summary, &out.Summary
		*out = new(RhodsQuickStartTaskSummary)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RhodsQuickStartTask.
func (in *RhodsQuickStartTask) DeepCopy() *RhodsQuickStartTask {
	if in == nil {
		return nil
	}
	out := new(RhodsQuickStartTask)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RhodsQuickStartTaskReview) DeepCopyInto(out *RhodsQuickStartTaskReview) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RhodsQuickStartTaskReview.
func (in *RhodsQuickStartTaskReview) DeepCopy() *RhodsQuickStartTaskReview {
	if in == nil {
		return nil
	}
	out := new(RhodsQuickStartTaskReview)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RhodsQuickStartTaskSummary) DeepCopyInto(out *RhodsQuickStartTaskSummary) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RhodsQuickStartTaskSummary.
func (in *RhodsQuickStartTaskSummary) DeepCopy() *RhodsQuickStartTaskSummary {
	if in == nil {
		return nil
	}
	out := new(RhodsQuickStartTaskSummary)
	in.DeepCopyInto(out)
	return out
}
